/*
 * generated by Xtext
 */
package org.cloudml.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CloudMLUiModule extends org.cloudml.dsl.ui.AbstractCloudMLUiModule {
	public CloudMLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
