/**
 * generated by Xtext
 */
package org.cloudml.dsl.ui.contentassist;

import org.cloudml.dsl.ui.contentassist.AbstractCloudMLProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class CloudMLProposalProvider extends AbstractCloudMLProposalProvider {
}
