/*
* generated by Xtext
*/
package org.cloudml.dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class CloudMLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.cloudml.dsl.ui.internal.CloudMLActivator.getInstance().getInjector("org.cloudml.dsl.CloudML");
	}
	
}
