/*
 * generated by Xtext
 */
package org.cloudml.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.cloudml.dsl.ui.internal.CloudMLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CloudMLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return CloudMLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return CloudMLActivator.getInstance().getInjector(CloudMLActivator.ORG_CLOUDML_DSL_CLOUDML);
	}
	
}
