/*
* generated by Xtext
*/
package org.cloudml.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.cloudml.dsl.services.CloudMLGrammarAccess;

public class CloudMLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private CloudMLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.cloudml.dsl.parser.antlr.internal.InternalCloudMLParser createParser(XtextTokenStream stream) {
		return new org.cloudml.dsl.parser.antlr.internal.InternalCloudMLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "CloudMLRoot";
	}
	
	public CloudMLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(CloudMLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
