/*
 * generated by Xtext
 */
package org.cloudml.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CloudMLRuntimeModule extends org.cloudml.dsl.AbstractCloudMLRuntimeModule {

}
