/*
* generated by Xtext
*/
package org.cloudml.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CloudMLStandaloneSetup extends CloudMLStandaloneSetupGenerated{

	public static void doSetup() {
		new CloudMLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

