/**
 * generated by Xtext
 */
package org.cloudml.dsl.validation;

import org.cloudml.dsl.validation.AbstractCloudMLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class CloudMLValidator extends AbstractCloudMLValidator {
}
